spring.application.name=smart-campus-api
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/smart_campus}
spring.data.mongodb.auto-index-creation=true
app.frontend-origin=${FRONTEND_ORIGIN:http://localhost:3000}
